rm_toxicity:
  seed: 1
  out_features: 7
  reward_model_name: gpt2
  loss_fn: cumulative_mse
  learning_rate: 2e-5
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-12
  weight_decay: 0.01
  warmup_steps: 1000
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 1
  eval_steps: 1000
  save_strategy: steps
  save_steps: 1000
  max_length: 256
  logging_steps: 100
  max_grad_norm: 2.0
  save_total_limit: 10
  dtype: float16
  datasets:
    - jigsaw_unintended_bias
  eval_size: 1000
  verbose: true
  log_wandb: false
  metrics: mse
  jigsaw_dir: ../datasets/PATH_TO_JIGSAW_DATASET
  output_dir: saved_models/gpt2_toxicity_backup


rm_sentiment:
  seed: 1
  out_features: 1
  reward_model_name: gpt2
  loss_fn: cumulative_mse
  learning_rate: 2e-5
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-12
  weight_decay: 0.01
  warmup_steps: 1000
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 1
  eval_steps: 1000
  save_strategy: steps
  save_steps: 1000
  max_length: 256
  logging_steps: 100
  max_grad_norm: 2.0
  save_total_limit: 10
  dtype: float16
  datasets:
    - sst2
    - amazon_polarity
  eval_size: 1000
  verbose: true
  log_wandb: false
  metrics: mse
  jigsaw_dir: null
  output_dir: "/home/jupyter-iec2024se10/Reward Decoding/models/rad_rm_sentiment"


gpt2-small:
  reward_model_name: /home/jupyter-iec2024se10/Reward Decoding/models/gpt2-small
  max_length: 256
  dtype: float16